apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kettle-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kettle-staging
    spec:
      containers:
      - name: kettle-staging
        image: gcr.io/k8s-testimages/kettle:test
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        - name: BUILD_LIMIT
          value: "1000"
        - name: DEPLOYMENT
          value: staging
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: service
        secret:
          secretName: kettle-service-account
      - name: data
        persistentVolumeClaim:
          claimName: kettle-data-staging
