apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kettle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kettle
    spec:
      containers:
      - name: kettle
        image: gcr.io/k8s-testimages/kettle:testtest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/service-account/service-account.json
        - name: DEPLOYMENT
          value: prod
        volumeMounts:
        - name: service
          mountPath: /etc/service-account
          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: service
        secret:
          secretName: kettle-service-account
      - name: data
        persistentVolumeClaim:
          claimName: kettle-data
