presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-unit
    annotations:
      testgrid-dashboards: sig-testing-misc
    decorate: true
    cluster: k8s-infra-prow-build
    skip_branches:
    - release-\d+.\d+ # per-release job
    labels:
      preset-service-account: "true"
    optional: true
    always_run: true
    path_alias: k8s.io/kubernetes
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210226-c001921-master
          command:
            - runner.sh
            - bash
            - -c
          args:
            # TODO: stop depending on custom timeout
            - 'make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=240s'
          # TODO: direct copy from pull-kubernetes-bazel-test, tune these
          resources:
            limits:
              cpu: 4
              memory: "36Gi"
            requests:
              cpu: 4
              memory: "36Gi"
  - name: pull-kubernetes-unit-experimental
    # try clonerefs with preclone
    decoration_config:
      utility_images:
        clonerefs: "gcr.io/spiffxp-gke-dev/clonerefs-k8s-preclone:latest"
    annotations:
      testgrid-dashboards: sig-testing-misc
    decorate: true
    cluster: k8s-infra-prow-build
    skip_branches:
    - release-\d+.\d+ # per-release job
    labels:
      preset-service-account: "true"
    optional: true
    always_run: false
    path_alias: k8s.io/kubernetes
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210226-c001921-master
          command:
            - runner.sh
            - bash
            - -c
          args:
            # TODO: stop depending on custom timeout
            - 'make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=240s'
          # TODO: direct copy from pull-kubernetes-bazel-test, tune these
          resources:
            limits:
              cpu: 4
              memory: "36Gi"
            requests:
              cpu: 4
              memory: "36Gi"
periodics:
  - interval: 1h
    name: ci-kubernetes-generate-make-test-cache
    annotations:
      testgrid-dashboards: sig-testing-canaries
    decorate: true
    extra_refs:
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210226-c001921-master
          command:
            - runner.sh
            - bash
          args:
            - -c
            - |
              result=0
              # Run the tests as usual
              time make test KUBE_TIMEOUT=--timeout=600s || result=$?
              # Send the cache off to gcs
              time tar -czf cache.tar.gz -C _output/local/go cache/ || result=$?
              time gsutil cp cache.tar.gz gs://kubernetes-jenkins/cache/poc/k8s-test-cache.tar.gz || result=$?
              exit $result
  - interval: 15m
    name: ci-kubernetes-cached-make-test
    annotations:
      testgrid-dashboards: sig-testing-canaries
    decorate: true
    extra_refs:
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    spec:
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20210226-c001921-master
          command:
            - runner.sh
            - bash
          args:
            - -c
            - |
              # Restore the cache
              time curl https://storage.googleapis.com/kubernetes-jenkins/cache/poc/k8s-test-cache.tar.gz -o cache.tar.gz
              mkdir -p _output/local/go/
              time tar -xzf cache.tar.gz -C _output/local/go
              # Run tests as usual
              time make test KUBE_TIMEOUT=--timeout=600s
